Repository Plemiona-2-5/api, pull requests merged in 2021-05, with the labels that each got.

#43 #22 Create endpoint to add a new tribe
  TribalWars/src/ApplicationCore/ApplicationCore.csproj
  TribalWars/src/ApplicationCore/DependencyInjection.cs
  TribalWars/src/ApplicationCore/Dtos/TribeDto.cs
  TribalWars/src/ApplicationCore/Interfaces/Repository/IBuildingRequiredRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Repository/ITribeRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Repository/IVillageBuildingRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Repository/IVillageMaterialRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Services/IBuildingRequiredService.cs
  TribalWars/src/ApplicationCore/Interfaces/Services/ITribeService.cs
  TribalWars/src/ApplicationCore/Resources/MessageResource.cs
  TribalWars/src/ApplicationCore/Resources/MessageResource.en-US.resx
  TribalWars/src/ApplicationCore/Responses/ErrorResponse.cs
  TribalWars/src/ApplicationCore/Responses/SuccessResponse.cs
  TribalWars/src/ApplicationCore/Services/BuildingRequiredService.cs
  TribalWars/src/ApplicationCore/Services/TribeService.cs
  TribalWars/src/Infrastructure/DependencyInjection.cs
  TribalWars/src/Infrastructure/Mapping/DtoToEntityProfile.cs
  TribalWars/src/Infrastructure/Repository/BuildingRequiredRepository.cs
  TribalWars/src/Infrastructure/Repository/TribeRepository.cs
  TribalWars/src/Infrastructure/Repository/VillageBuildingRepository.cs
  TribalWars/src/Infrastructure/Repository/VillageMaterialRepository.cs
  TribalWars/src/WebApi/Controllers/TribeController.cs
  TribalWars/src/WebApi/Startup.cs
  TribalWars/src/WebApi/appsettings.json
Labels: Endpoint

#46 #23 Endpoint to get tribe information
  TribalWars/src/ApplicationCore/Interfaces/Repository/ITribeRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Repository/ITribeUserRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Services/ITribeService.cs
  TribalWars/src/ApplicationCore/Resources/MessageResource.en-US.resx
  TribalWars/src/ApplicationCore/Results/Generic/ServiceResult.cs
  TribalWars/src/ApplicationCore/Services/TribeService.cs
  TribalWars/src/ApplicationCore/ViewModels/TribeDetailsVM.cs
  TribalWars/src/Infrastructure/DependencyInjection.cs
  TribalWars/src/Infrastructure/Repository/TribeRepository.cs
  TribalWars/src/Infrastructure/Repository/TribeUserRepository.cs
  TribalWars/src/WebApi/Controllers/TribeController.cs
Labels: Endpoint

#49 Fix VillageMaterialRepository
  TribalWars/src/ApplicationCore/Interfaces/Repository/IVillageMaterialRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Services/IVillageMaterialRepository.cs
  TribalWars/src/ApplicationCore/Services/BuildingRequiredService.cs
  TribalWars/src/Infrastructure/Repository/VillageMaterialRepository.cs
Labels: bug

#53 edit description, get details
  TribalWars/src/ApplicationCore/Results/Generic/ServiceResult.cs
  TribalWars/src/ApplicationCore/Services/TribeService.cs
  TribalWars/src/WebApi/Controllers/TribeController.cs
Labels: bug

#58 worker error repair
  TribalWars/src/WebApi/Hubs/BuildingsQueueHub.cs
  TribalWars/src/WebApi/Workers/BuildingsQueueTimerWorker.cs
Labels: bug

#56 #25 display tribe members list
  TribalWars/src/ApplicationCore/DependencyInjection.cs
  TribalWars/src/ApplicationCore/Interfaces/Services/ITribeMemberService.cs
  TribalWars/src/ApplicationCore/Resources/MessageResource.en-US.resx
  TribalWars/src/ApplicationCore/Results/Generic/ServiceResult.cs
  TribalWars/src/ApplicationCore/Services/TribeMemberService.cs
  TribalWars/src/ApplicationCore/Services/TribeService.cs
  TribalWars/src/ApplicationCore/ViewModels/TribeMemberVM.cs
  TribalWars/src/Infrastructure/Mapping/EntityToViewModelProfile.cs
  TribalWars/src/WebApi/Controllers/TribeController.cs
Labels: Endpoint

#59 Add tribe member
  TribalWars/src/ApplicationCore/Dtos/InviteTribeMemberDto.cs
  TribalWars/src/ApplicationCore/Interfaces/Repository/IPlayerRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Repository/ITribeUserRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Services/ITribeMemberService.cs
  TribalWars/src/ApplicationCore/Resources/MessageResource.en-US.resx
  TribalWars/src/ApplicationCore/Services/TribeMemberService.cs
  TribalWars/src/Infrastructure/DependencyInjection.cs
  TribalWars/src/Infrastructure/Repository/PlayerRepository.cs
  TribalWars/src/Infrastructure/Repository/TribeUserRepository.cs
  TribalWars/src/WebApi/Controllers/TribeController.cs
Labels: Endpoint

#61 add building to queue
  TribalWars/src/ApplicationCore/Interfaces/IBuildingsQueueRepository.cs
  TribalWars/src/ApplicationCore/Services/BuildingsQueueService.cs
  TribalWars/src/Infrastructure/Repository/BuildingsQueueRepository.cs
Labels: Functionality

#63 Edit cors
  TribalWars/src/WebApi/Startup.cs
Labels: bug

#66 #28 Disband tribe
  TribalWars/src/ApplicationCore/Dtos/DisbandTribeDto.cs
  TribalWars/src/ApplicationCore/Interfaces/Repository/ITribeRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Repository/ITribeUserRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Services/ITribeMemberService.cs
  TribalWars/src/ApplicationCore/Interfaces/Services/ITribeService.cs
  TribalWars/src/ApplicationCore/Resources/MessageResource.en-US.resx
  TribalWars/src/ApplicationCore/Services/TribeService.cs
  TribalWars/src/Infrastructure/Configuration/TribeConfig.cs
  TribalWars/src/Infrastructure/Repository/TribeRepository.cs
  TribalWars/src/Infrastructure/Repository/TribeUserRepository.cs
  TribalWars/src/WebApi/Controllers/TribeController.cs
Labels: Endpoint

#68 Fix remove tribe member
  TribalWars/src/ApplicationCore/Services/TribeMemberService.cs
Labels: bug

#65 #29 Leave the tribe
  TribalWars/src/ApplicationCore/Interfaces/Services/ITribeMemberService.cs
  TribalWars/src/ApplicationCore/Resources/MessageResource.en-US.resx
  TribalWars/src/ApplicationCore/Services/TribeMemberService.cs
  TribalWars/src/WebApi/Controllers/TribeController.cs
Labels: Endpoint

#69 Fix leave the tribe
  TribalWars/src/ApplicationCore/Resources/MessageResource.en-US.resx
  TribalWars/src/ApplicationCore/Services/TribeMemberService.cs
Labels: bug

#71 Fix building queue service method
  TribalWars/src/ApplicationCore/Services/BuildingsQueueService.cs
Labels: bug

#72 #16 Get village location
  TribalWars/src/ApplicationCore/DependencyInjection.cs
  TribalWars/src/ApplicationCore/Interfaces/Repository/IVillageRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Services/IVillageService.cs
  TribalWars/src/ApplicationCore/Resources/MessageResource.en-US.resx
  TribalWars/src/ApplicationCore/Services/VillageService.cs
  TribalWars/src/ApplicationCore/ViewModels/CoordinatesVM.cs
  TribalWars/src/Infrastructure/DependencyInjection.cs
  TribalWars/src/Infrastructure/Mapping/EntityToViewModelProfile.cs
  TribalWars/src/Infrastructure/Repository/VillageRepository.cs
  TribalWars/src/WebApi/Controllers/BuildingController.cs
  TribalWars/src/WebApi/Controllers/RequiredBuildingsController.cs
  TribalWars/src/WebApi/Controllers/VillageController.cs
Labels: Endpoint

#73 #18 Get number of army units
  TribalWars/src/ApplicationCore/DependencyInjection.cs
  TribalWars/src/ApplicationCore/Interfaces/Repository/IVillageUnitRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Services/IVillageUnitService.cs
  TribalWars/src/ApplicationCore/Services/VillageUnitService.cs
  TribalWars/src/ApplicationCore/ViewModels/VillageUnitVM.cs
  TribalWars/src/Infrastructure/DependencyInjection.cs
  TribalWars/src/Infrastructure/Mapping/EntityToViewModelProfile.cs
  TribalWars/src/Infrastructure/Repository/VillageUnitRepository.cs
  TribalWars/src/WebApi/Controllers/RequiredBuildingsController.cs
  TribalWars/src/WebApi/Controllers/VillageUnitController.cs
Labels: Endpoint

#74 #17 Get building queue
  TribalWars/src/ApplicationCore/Interfaces/IBuildingsQueueRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/IBuildingsQueueService.cs
  TribalWars/src/ApplicationCore/Services/BuildingsQueueService.cs
  TribalWars/src/ApplicationCore/ViewModels/BuildingQueueVM.cs
  TribalWars/src/Infrastructure/Mapping/EntityToViewModelProfile.cs
  TribalWars/src/Infrastructure/Repository/BuildingsQueueRepository.cs
  TribalWars/src/WebApi/Controllers/BuildingController.cs
Labels: Endpoint

#79 #78 Get village buildings
  TribalWars/src/ApplicationCore/Interfaces/Repository/IVillageBuildingRepository.cs
  TribalWars/src/ApplicationCore/Interfaces/Services/IVillageService.cs
  TribalWars/src/ApplicationCore/Services/VillageService.cs
  TribalWars/src/ApplicationCore/ViewModels/VillageBuildingVM.cs
  TribalWars/src/Infrastructure/Mapping/EntityToViewModelProfile.cs
  TribalWars/src/Infrastructure/Repository/VillageBuildingRepository.cs
  TribalWars/src/WebApi/Controllers/VillageController.cs
Labels: Endpoint

#81 add tribe id to tribe details
  TribalWars/src/ApplicationCore/Services/TribeService.cs
  TribalWars/src/ApplicationCore/ViewModels/TribeDetailsVM.cs
Labels: enhancement
